spring.application.name=apiOzonio

server.port=9090

# Modbus
modbus.host=192.168.1.101
modbus.port=502
modbus.poll-ms=1000


# CORS (ajuste o domínio do Altus Web Server/front)
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,OPTIONS
