spring.application.name=apiOzonio

server.port=9090

# Modbus
modbus.host=192.168.100.101
modbus.port=502
modbus.poll-ms=1000

# Mapa de tags (opção 1 rápida: CSV-like)
tags.config=\
  flow:HR:40001:int16:1:0.1|\
  pressure:HR:40002:int16:1:0.01|\
  ozonio_ppm:IR:30001:int16:1:0.01

# CORS (ajuste o domínio do Altus Web Server/front)
spring.web.cors.allowed-origins=http://altus-web:port,http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,OPTIONS
